-- Run this after deploying the Edge Function and setting RUN_SIGNAL_BOT_SECRET.
-- Replace the project URL and secret before executing.
--
-- select cron.unschedule('run-signal-bot-market-hours');
--
-- select cron.schedule(
--   'run-signal-bot-market-hours',
--   '*/15 0-6 * * 1-5',
--   $$
--   select net.http_post(
--     url := 'https://brdlwwoyunxvigkaxhav.supabase.co/functions/v1/run-signal-bot',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'x-bot-secret', 'REPLACE_WITH_RUN_SIGNAL_BOT_SECRET'
--     ),
--     body := '{}'::jsonb
--   );
--   $$
-- );

